'use strict';

/**
 * Agent module contract. Every agent module in this directory must export
 * an object matching this shape. The registry loads them dynamically and
 * wraps each in try/catch — a broken module never crashes the CLI.
 *
 * Required exports:
 *   name    {string}   — Human-readable name (e.g., "Claude Code")
 *   id      {string}   — Machine ID, matches --agent flag (e.g., "claude-code")
 *   tier    {number}   — the Solid-vs-Advise tier, computed by computeExpectedTier()
 *                         below from the three declared capability fields — see
 *                         plan 21-06 (ticket G-1661). This line previously
 *                         described tier 2 as requiring both an ignore file AND
 *                         the agent's settings file, which was false of every
 *                         shipped module: no tier-2 module writes to the agent's
 *                         own settings file, and it could not distinguish tier 2
 *                         from tier 3 (two tier-3 modules also write ignore files).
 *   detect  {function} — Returns { found: bool, version?: string, path?: string }
 *   harden  {function} — Applies hardening. Args: (projectDir, flags). Returns { actions: string[], warnings: string[] }
 *   audit   {function} — Checks posture. Returns { checks: Array<{name, pass, detail}>, level: number }
 *
 * Declared capability fields (consumed by computeExpectedTier(), also required):
 *   installsEnforcedHooks {boolean}         — true iff harden() installs the
 *     agent's own hook/interception system and wires it into the agent's
 *     settings file (today, only claude-code.js).
 *   writesIgnoreFile      {boolean}         — true iff harden() writes a
 *     persistent ignore file (e.g. .cursorignore).
 *   ignoreFileHonored     {boolean | null}  — whether the agent's own
 *     documented behavior is CITED as honoring that ignore file. This is a
 *     per-module declared + cited fact, never a runtime probe — third-party
 *     agents cannot be exercised in this repository's CI. `null` means "no
 *     ignore file is written"; it is the only legal value when
 *     writesIgnoreFile is false.
 *
 * Relational invariants (violating either throws — see computeExpectedTier()):
 *   - writesIgnoreFile: false requires ignoreFileHonored === null.
 *   - ignoreFileHonored !== null requires writesIgnoreFile: true.
 *
 * The predicate (in order — hook installation is checked first and dominates
 * an honored ignore file):
 *   1. installsEnforcedHooks           -> tier 1
 *   2. writesIgnoreFile && ignoreFileHonored === true -> tier 2
 *   3. otherwise                       -> tier 3
 */

// Helper: check if a CLI command exists
// Uses execFileSync to avoid shell injection (C-1 fix)
function commandExists(cmd) {
  const { execFileSync } = require('child_process');
  if (!/^[a-zA-Z0-9_-]+$/.test(cmd)) return false; // reject suspicious names
  try {
    execFileSync('which', [cmd], { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

// Helper: get CLI version
// Uses execFileSync to avoid shell injection (C-1 fix)
function getVersion(cmd, versionFlag) {
  const { execFileSync } = require('child_process');
  if (!/^[a-zA-Z0-9_-]+$/.test(cmd)) return null;
  try {
    const out = execFileSync(cmd, [versionFlag || '--version'], {
      stdio: 'pipe',
      timeout: 5000,
    });
    return out.toString().trim().split('\n')[0];
  } catch {
    return null;
  }
}

// Helper: check if macOS app exists
function macAppExists(appName) {
  const fs = require('fs');
  const paths = [
    `/Applications/${appName}.app`,
    `${require('os').homedir()}/Applications/${appName}.app`,
  ];
  return paths.find(p => fs.existsSync(p)) || null;
}

// Helper: check if VS Code extension is installed
function vscodeExtensionExists(extensionId) {
  const fs = require('fs');
  const os = require('os');
  const path = require('path');
  const extDir = path.join(os.homedir(), '.vscode', 'extensions');
  try {
    const dirs = fs.readdirSync(extDir);
    return dirs.some(d => d.toLowerCase().startsWith(extensionId.toLowerCase()));
  } catch {
    return false;
  }
}

// Helper: write an ignore file if it doesn't exist
// Pass dryRun: true to check without writing
function writeIgnoreFile(projectDir, filename, patterns, dryRun) {
  const fs = require('fs');
  const path = require('path');
  const filePath = path.join(projectDir, filename);

  if (dryRun) {
    return { written: false, path: filePath, reason: 'dry-run' };
  }

  // H-1: Resolve symlinks and reject system directories
  const resolved = fs.realpathSync(projectDir);
  if (['/', '/etc', '/usr', '/System', '/Library'].some(p => resolved === p || resolved.startsWith(p + '/'))) {
    return { written: false, path: filePath, reason: 'refused to write to system directory' };
  }

  const header = `# Generated by llm-safe-haven — exclude sensitive files from AI context\n`;
  const content = header + patterns.join('\n') + '\n';

  // M-5: Use exclusive creation (O_CREAT|O_EXCL) to avoid TOCTOU race condition
  try {
    fs.writeFileSync(filePath, content, { flag: 'wx' });
    return { written: true, path: filePath };
  } catch (err) {
    if (err.code === 'EEXIST') {
      return { written: false, path: filePath, reason: 'already exists' };
    }
    throw err;
  }
}

// Standard sensitive patterns for ignore files
const SENSITIVE_PATTERNS = [
  '# Secrets and credentials',
  '.env',
  '.env.*',
  '!.env.example',
  '!.env.template',
  '',
  '# Private keys',
  '*.pem',
  '*.key',
  'id_rsa',
  'id_ed25519',
  '',
  '# Credential files',
  'credentials.json',
  'service-account*.json',
  '**/secrets.yaml',
  '**/secrets.yml',
  '**/.secret',
  '**/.secrets',
  '',
  '# Cloud provider credentials',
  '.aws/credentials',
  '.config/gcloud/',
  '.kube/config',
];

// The codified Solid-vs-Advise predicate (G-1661, plan 21-06). Pure function
// of a module's three declared capability fields — see the contract
// doc-comment above. Never reads the module's own `tier` field: a predicate
// that consults the answer it is checking is vacuous.
function computeExpectedTier(capabilities) {
  if (!capabilities || typeof capabilities !== 'object') {
    throw new TypeError(
      'computeExpectedTier: expected an object with installsEnforcedHooks, ' +
      'writesIgnoreFile, ignoreFileHonored'
    );
  }

  // Stage 1 — presence. No default for any field: a module that never
  // declared its capabilities must not silently satisfy whatever tier it
  // happens to state.
  const REQUIRED_FIELDS = ['installsEnforcedHooks', 'writesIgnoreFile', 'ignoreFileHonored'];
  for (const field of REQUIRED_FIELDS) {
    if (!Object.prototype.hasOwnProperty.call(capabilities, field)) {
      throw new TypeError(`computeExpectedTier: missing required capability field "${field}"`);
    }
  }

  const { installsEnforcedHooks, writesIgnoreFile, ignoreFileHonored } = capabilities;

  // Stage 2 — type.
  if (typeof installsEnforcedHooks !== 'boolean') {
    throw new TypeError(
      `computeExpectedTier: "installsEnforcedHooks" must be a boolean, got ${typeof installsEnforcedHooks}`
    );
  }
  if (typeof writesIgnoreFile !== 'boolean') {
    throw new TypeError(
      `computeExpectedTier: "writesIgnoreFile" must be a boolean, got ${typeof writesIgnoreFile}`
    );
  }
  if (ignoreFileHonored !== null && typeof ignoreFileHonored !== 'boolean') {
    throw new TypeError(
      `computeExpectedTier: "ignoreFileHonored" must be a boolean or null, got ${typeof ignoreFileHonored}`
    );
  }

  // Stage 3 — relational coherence. The three fields are not independent; a
  // contradictory combination throws naming both offending fields rather
  // than silently resolving to tier 3 (the worst possible outcome — an
  // internally-inconsistent declaration would present as a correctly-graded
  // Advise agent).
  if (writesIgnoreFile === false && ignoreFileHonored !== null) {
    throw new TypeError(
      'computeExpectedTier: contradictory capability declaration — ' +
      `"writesIgnoreFile" is false but "ignoreFileHonored" is ${JSON.stringify(ignoreFileHonored)}; ` +
      'a module that writes no ignore file cannot carry a verdict about one being honored ' +
      '("writesIgnoreFile": false requires "ignoreFileHonored" === null)'
    );
  }
  if (writesIgnoreFile === true && ignoreFileHonored === null) {
    throw new TypeError(
      'computeExpectedTier: contradictory capability declaration — ' +
      '"writesIgnoreFile" is true but "ignoreFileHonored" is null; an honored-ness verdict ' +
      'is required once a file is written ("ignoreFileHonored" !== null requires ' +
      '"writesIgnoreFile" === true)'
    );
  }

  // Stage 4 — resolution, over the six coherent states only. Hook
  // installation is checked first and dominates: a module that both
  // installs hooks and writes an honored ignore file is unambiguously tier
  // 1. Strict equality against `true` for the honored flag so a truthy
  // non-boolean can never reach the tier-2 branch (unreachable in practice
  // after stage 2, kept as defense in depth).
  if (installsEnforcedHooks) return 1;
  if (writesIgnoreFile && ignoreFileHonored === true) return 2;
  return 3;
}

module.exports = {
  commandExists,
  getVersion,
  macAppExists,
  vscodeExtensionExists,
  writeIgnoreFile,
  SENSITIVE_PATTERNS,
  computeExpectedTier,
};
