'use strict';

/**
 * Agent module contract. Every agent module in this directory must export
 * an object matching this shape. The registry loads them dynamically and
 * wraps each in try/catch — a broken module never crashes the CLI.
 *
 * Required exports:
 *   name    {string}   — Human-readable name (e.g., "Claude Code")
 *   id      {string}   — Machine ID, matches --agent flag (e.g., "claude-code")
 *   tier    {number}   — 1=full (hooks+settings), 2=solid (ignore+settings), 3=advise-only
 *   detect  {function} — Returns { found: bool, version?: string, path?: string }
 *   harden  {function} — Applies hardening. Args: (projectDir, flags). Returns { actions: string[], warnings: string[] }
 *   audit   {function} — Checks posture. Returns { checks: Array<{name, pass, detail}>, level: number }
 */

// Helper: check if a CLI command exists
// Uses execFileSync to avoid shell injection (C-1 fix)
function commandExists(cmd) {
  const { execFileSync } = require('child_process');
  if (!/^[a-zA-Z0-9_-]+$/.test(cmd)) return false; // reject suspicious names
  try {
    execFileSync('which', [cmd], { stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

// Helper: get CLI version
// Uses execFileSync to avoid shell injection (C-1 fix)
function getVersion(cmd, versionFlag) {
  const { execFileSync } = require('child_process');
  if (!/^[a-zA-Z0-9_-]+$/.test(cmd)) return null;
  try {
    const out = execFileSync(cmd, [versionFlag || '--version'], {
      stdio: 'pipe',
      timeout: 5000,
    });
    return out.toString().trim().split('\n')[0];
  } catch {
    return null;
  }
}

// Helper: check if macOS app exists
function macAppExists(appName) {
  const fs = require('fs');
  const paths = [
    `/Applications/${appName}.app`,
    `${require('os').homedir()}/Applications/${appName}.app`,
  ];
  return paths.find(p => fs.existsSync(p)) || null;
}

// Helper: check if VS Code extension is installed
function vscodeExtensionExists(extensionId) {
  const fs = require('fs');
  const os = require('os');
  const path = require('path');
  const extDir = path.join(os.homedir(), '.vscode', 'extensions');
  try {
    const dirs = fs.readdirSync(extDir);
    return dirs.some(d => d.toLowerCase().startsWith(extensionId.toLowerCase()));
  } catch {
    return false;
  }
}

// Helper: write an ignore file if it doesn't exist
// Pass dryRun: true to check without writing
function writeIgnoreFile(projectDir, filename, patterns, dryRun) {
  const fs = require('fs');
  const path = require('path');
  const filePath = path.join(projectDir, filename);

  if (fs.existsSync(filePath)) {
    return { written: false, path: filePath, reason: 'already exists' };
  }

  if (dryRun) {
    return { written: false, path: filePath, reason: 'dry-run' };
  }

  // H-1: Resolve symlinks and reject system directories
  const resolved = fs.realpathSync(projectDir);
  if (['/', '/etc', '/usr', '/System', '/Library'].some(p => resolved === p || resolved.startsWith(p + '/'))) {
    return { written: false, path: filePath, reason: 'refused to write to system directory' };
  }

  const header = `# Generated by llm-safe-haven — exclude sensitive files from AI context\n`;
  const content = header + patterns.join('\n') + '\n';
  fs.writeFileSync(filePath, content);
  return { written: true, path: filePath };
}

// Standard sensitive patterns for ignore files
const SENSITIVE_PATTERNS = [
  '# Secrets and credentials',
  '.env',
  '.env.*',
  '!.env.example',
  '!.env.template',
  '',
  '# Private keys',
  '*.pem',
  '*.key',
  'id_rsa',
  'id_ed25519',
  '',
  '# Credential files',
  'credentials.json',
  'service-account*.json',
  '**/secrets.yaml',
  '**/secrets.yml',
  '**/.secret',
  '**/.secrets',
  '',
  '# Cloud provider credentials',
  '.aws/credentials',
  '.config/gcloud/',
  '.kube/config',
];

module.exports = {
  commandExists,
  getVersion,
  macAppExists,
  vscodeExtensionExists,
  writeIgnoreFile,
  SENSITIVE_PATTERNS,
};
